#Pod Creation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template:
    metadata:
       labels:
        app: auth
    spec:
       containers:
         - name: auth
           image: snuus/auth
           env: 
             - name: MONGO_URI
               value: 'mongodb://auth-mongo-srv:27017/auth_v1'
             - name: JWT_KEY
               valueFrom:
                 secretKeyRef: 
                    name: jwt-key
                    key: JWT_KEY
---
#Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports: 
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000